export enum QueryKeyEnum {
    COVER_LETTERS_GET = 'COVER_LETTERS_GET',
    INTERVIEW_QUESTIONS_GET = 'INTERVIEW_QUESTIONS_GET',
    INTERVIEW_QUESTIONS_SUBMIT = 'INTERVIEW_QUESTIONS_SUBMIT',
    SUBMIT_APP = 'SUBMIT_APP',
    SUBMIT_CONTACT = 'SUBMIT_CONTACT',
}
